OC-8537: additional sanity checks for symlinks
- make sure to clean up symlinks before installing
- make sure to check that symlinks really exist after installation

diff --git a/jenkins/client-test b/jenkins/client-test
--- a/jenkins/client-test
+++ b/jenkins/client-test
@@ -16,22 +16,29 @@ exists()
   fi
 }
 
+# SmartOS builds in /opt/local instead
+is_smartos()
+{
+  uname -v | grep "^joyent" 2>&1>/dev/null
+}
+
+if is_smartos; then
+    PREFIX="/opt/local"
+else
+    PREFIX="/usr"
+fi
+
 # copy off the timestamp for fingerprinting before we blow it away later
 mv $BUILD_NUMBER/build_timestamp $WORKSPACE/
 cd $BUILD_NUMBER
 
 # remove the chef package / clobber the files
-# then install the new package
 if exists dpkg;
 then
     sudo dpkg -P chef || true
-    sudo rm -rf /opt/chef/*
-    sudo dpkg -i pkg/chef*.deb
 elif exists rpm;
 then
     sudo rpm -ev chef || true
-    sudo rm -rf /opt/chef/*
-    sudo rpm -Uvh pkg/chef*.rpm
 elif exists pkgadd;
 then
     cat <<EOF > /tmp/nocheck
@@ -41,13 +48,54 @@ EOF
     sudo pkgrm -a /tmp/nocheck -n chef || true
     # BUGBUG: we have to do this twice because the postrm fails the first time
     sudo pkgrm -a /tmp/nocheck -n chef || true
-    sudo rm -rf /opt/chef/*
-    # BUGBUG: we don't remove symlinks correctly so the install fails the next time
-    sudo pkgadd -n -d pkg/chef*.solaris -a /tmp/nocheck chef || true
 else # makeself installer
-    sudo rm  -rf /opt/chef/*
-    # BUGBUG: without an uninstaller the makeself installer fails when creating symlinks
+  :  # intentionally left blank
+fi
+
+sudo rm -rf /opt/chef/*
+
+# ensure symlinks are gone, so that failures to recreate them get caught
+sudo rm -f $PREFIX/bin/chef-client || true
+sudo rm -f $PREFIX/bin/chef-solo || true
+sudo rm -f $PREFIX/bin/chef-apply || true
+sudo rm -f $PREFIX/bin/chef-shell || true
+sudo rm -f $PREFIX/bin/knife || true
+sudo rm -f $PREFIX/bin/shef || true
+sudo rm -f $PREFIX/bin/ohai || true
+
+# install the new package
+if exists dpkg;
+then
+    sudo dpkg -i pkg/chef*.deb
+elif exists rpm;
+then
+    sudo rpm -Uvh pkg/chef*.rpm
+elif exists pkgadd;
+then
+    sudo pkgadd -n -d pkg/chef*.solaris -a /tmp/nocheck chef
+else # makeself installer
     sudo ./pkg/chef*.sh || true
+fi
+
+# sanity check that we're getting symlinks from the pre-install script
+if [ ! -e "/usr/bin/chef-client" ]; then
+  echo "/usr/bin/chef-client symlink was not installed by pre-install script!"
+  exit 1
+fi
+
+if [ ! -e "/usr/bin/knife" ]; then
+  echo "/usr/bin/knife symlink was not installed by pre-install script!"
+  exit 1
+fi
+
+if [ ! -e "/usr/bin/chef-solo" ]; then
+  echo "/usr/bin/chef-solo symlink was not installed by pre-install script!"
+  exit 1
+fi
+
+if [ ! -e "/usr/bin/ohai" ]; then
+  echo "/usr/bin/ohai symlink was not installed by pre-install script!"
+  exit 1
 fi
 
 # we test using the specs packaged in the gem
